// `--rotate best`'s orientation decision, ported from
// `pipeline/handstand/pose_mediapipe.py` (chainlink #45): which of the two
// VIDEO-mode passes (upright / 180°-rotated) each frame's keypoints come from.
//
// The thresholds, the reference and the scorer were all built on the
// keypoints `--rotate best` wrote, so the phone has to make this decision the
// *same* way Python does — over the whole clip, not frame by frame. The four
// functions below are the Python functions step for step:
//
//   * `frameMargin`      <- `frame_margin`
//   * `smoothMargin`     <- `smooth_margin`
//   * `openingOrientation` <- `_opening_orientation`
//   * `chooseOrientations` <- `choose_orientations`
//
// with the same constants (`ORIENT_WINDOW_S`, `ORIENT_MARGIN`,
// `ORIENT_MIN_SWITCH_S`), which `OrientationChooserTests` pins against both
// this file and the Python fixture `orientation_cases.json` (generated by
// `pipeline/handstand/orientation_cases.py` — the Swift test must reproduce
// Python's answers exactly, parity check only, chainlink #80).
//
// This file also holds the 33 -> 15 landmark index map: which MediaPipe
// landmark each schema `Joint` is (`JOINT_NAMES` / `TRACKED_JOINTS` on the
// Python side), and the 12 `MAIN_JOINTS` landmark indices the per-frame
// score is the mean visibility of.
//
// Pure maths over `Double`, no I/O — `swift test` covers all of it.

import Foundation

/// The MediaPipe pose landmark indices of the 15 schema joints, keyed by
/// `Joint` — the 33-to-15 map `pose_mediapipe.py` performs via `JOINT_NAMES`
/// (`nose` 0, shoulders 11/12, elbows 13/14, wrists 15/16, hips 23/24, knees
/// 25/26, ankles 27/28, foot indexes 31/32). The other 18 landmarks (eyes,
/// ears, mouth, fingers, heels) are deliberately absent, exactly as the
/// schema omits them. The app's MediaPipe extractor (chainlink #45) maps its
/// 33-landmark detections through this table.
public let mediaPipeLandmarkIndex: [Joint: Int] = [
    .nose: 0,
    .leftShoulder: 11,
    .rightShoulder: 12,
    .leftElbow: 13,
    .rightElbow: 14,
    .leftWrist: 15,
    .rightWrist: 16,
    .leftHip: 23,
    .rightHip: 24,
    .leftKnee: 25,
    .rightKnee: 26,
    .leftAnkle: 27,
    .rightAnkle: 28,
    .leftFootIndex: 31,
    .rightFootIndex: 32,
]

/// `--rotate best`'s per-clip orientation choice: the port of
/// `handstand.pose_mediapipe.choose_orientations` and its helpers.
///
/// Both passes of every frame are in before this runs (a clip-level
/// extractor, `MediaPipeClipExtractor` in the app, does the two passes), then
/// this picks, per frame, which pass's keypoints to keep: the margin
/// (`score_rotated - score_upright`) smoothed over a centred half-second of
/// **clip time**, the clip opening in the orientation that implies, and a
/// switch only once the smoothed margin has held the other sign by more than
/// `ORIENT_MARGIN` for `ORIENT_MIN_SWITCH_S`. A tie, a margin inside the
/// band, an unscored frame and a one-frame confident misread all keep the
/// orientation the clip is already in — see the Python docstrings for the
/// full reasoning (chainlink #79).
public enum OrientationChooser {
    /// `ORIENT_WINDOW_S` — width of the centred smoothing window, in seconds
    /// of clip time. Time, not frames: these clips are variable frame rate.
    public static let windowS = 0.5
    /// `ORIENT_MARGIN` — how much surer of one pass the model must be before
    /// the margin counts as a preference at all (0.05).
    public static let margin = 0.05
    /// `ORIENT_MIN_SWITCH_S` — how long such a preference must hold, in
    /// seconds, before the orientation actually switches (0.3).
    public static let minSwitchS = 0.3

    /// How many landmarks one MediaPipe pose has (`len(JOINT_NAMES)`).
    public static let landmarkCount = 33

    /// `MAIN_JOINTS`' landmark indices, in schema order: shoulders, elbows,
    /// wrists, hips, knees, ankles — the 12 landmarks a pass's per-frame
    /// score is the mean visibility of (`MAIN_JOINT_INDEX` in Python).
    public static let mainJointIndices: [Int] = [11, 12, 13, 14, 15, 16, 23, 24, 25, 26, 27, 28]

    /// `frame_margin`: `score_rotated - score_upright` per frame — which pass
    /// the model is surer of. A frame one pass could not score has **no**
    /// margin (NaN), not a margin of infinity: `+inf - inf` and any operand
    /// that is not finite come out NaN, which is what makes such a frame
    /// ignorable rather than decisive.
    ///
    /// Precondition: one score per frame, as Python's `ValueError`.
    public static func frameMargin(
        scoreUpright: [Double],
        scoreRotated: [Double]
    ) -> [Double] {
        precondition(
            scoreUpright.count == scoreRotated.count,
            "expected one score per frame, got \(scoreUpright.count) upright and "
                + "\(scoreRotated.count) rotated"
        )
        return zip(scoreUpright, scoreRotated).map { upright, rotated in
            let value = rotated - upright
            return value.isFinite ? value : Double.nan
        }
    }

    /// `smooth_margin`: a centred moving average of the frame margin over a
    /// `windowS`-second window of **clip time** (`tMs` is the clip's
    /// millisecond clock, strictly increasing).
    ///
    /// NaN margins (frames one or both passes could not score) are skipped,
    /// not counted as zero; a frame with no scorable neighbour inside its
    /// window stays NaN — "no evidence here". The window bounds are
    /// `searchsorted` on the timestamps: frames within
    /// `[t - half, t + half]`, inclusive on both ends, so the smoothing is
    /// symmetric in time whatever the frame rate did to the frame spacing.
    ///
    /// Precondition: one margin per frame, as Python's `ValueError`.
    public static func smoothMargin(
        tMs: [Double],
        margin: [Double],
        windowS: Double = OrientationChooser.windowS
    ) -> [Double] {
        precondition(
            tMs.count == margin.count,
            "expected one margin per frame, got \(margin.count) for \(tMs.count) frames"
        )
        guard !tMs.isEmpty else { return [] }
        // The window is in seconds, the timestamps in milliseconds.
        let halfMs = max(windowS, 0.0) * 1000.0 / 2.0
        var smoothed = [Double](repeating: Double.nan, count: tMs.count)
        for (index, t) in tMs.enumerated() {
            let first = lowerBound(tMs, t - halfMs)
            let last = upperBound(tMs, t + halfMs)
            var sum = 0.0
            var count = 0
            for value in margin[first..<last] where value.isFinite {
                sum += value
                count += 1
            }
            if count > 0 {
                smoothed[index] = sum / Double(count)
            }
        }
        return smoothed
    }

    /// `_opening_orientation`: the orientation a clip starts in — the sign of
    /// its opening smoothed margin over the first `ORIENT_WINDOW_S` of clip
    /// time. A tie, no evidence, or an opening that ends before any frame is
    /// scored starts the clip **upright** (`false`), like `auto`'s first
    /// frame.
    public static func openingOrientation(tMs: [Double], smoothed: [Double]) -> Bool {
        precondition(
            tMs.count == smoothed.count,
            "expected one smoothed margin per frame, got \(smoothed.count) for \(tMs.count)"
        )
        guard let first = tMs.first else { return false }
        let openingEnd = upperBound(tMs, first + windowS * 1000.0)
        var sum = 0.0
        var count = 0
        for value in smoothed[..<openingEnd] where value.isFinite {
            sum += value
            count += 1
        }
        guard count > 0 else { return false }
        return sum / Double(count) > 0.0
    }

    /// `choose_orientations`: one `rotated` flag per frame, in frame order —
    /// the answer `--rotate best`'s `rotated` column holds.
    ///
    /// The margin is smoothed (1), the clip opens in the smoothed sign (2),
    /// and the orientation only **switches** once the smoothed margin has
    /// held the other sign, by more than `ORIENT_MARGIN`, for
    /// `ORIENT_MIN_SWITCH_S` (3). The sustained runs switch on the frame
    /// where the preference has held long enough, not afterwards.
    ///
    /// Precondition: one score per frame.
    public static func chooseOrientations(
        tMs: [Double],
        scoreUpright: [Double],
        scoreRotated: [Double]
    ) -> [Bool] {
        let smoothed = smoothMargin(
            tMs: tMs,
            margin: frameMargin(scoreUpright: scoreUpright, scoreRotated: scoreRotated)
        )
        guard !smoothed.isEmpty else { return [] }

        var rotated = openingOrientation(tMs: tMs, smoothed: smoothed)
        var choices = [Bool](repeating: false, count: smoothed.count)
        /// The orientation a switch is currently being tested for, and the
        /// time the test started; `nil` while no switch is in the offing.
        var pending: Bool?
        var pendingSince = 0.0
        for (index, value) in smoothed.enumerated() {
            let wantsRotation = value > 0.0  // NaN compares false, as in Python
            if value.isFinite, abs(value) > margin, wantsRotation != rotated {
                if pending == nil || pending != wantsRotation {
                    pending = wantsRotation
                    pendingSince = tMs[index]
                } else if tMs[index] - pendingSince >= minSwitchS * 1000.0 {
                    rotated = pending ?? rotated
                    pending = nil
                }
            } else {
                pending = nil
            }
            choices[index] = rotated
        }
        return choices
    }

    // MARK: - searchsorted, as numpy spells it

    /// `np.searchsorted(times, target, side="left")`: the first index whose
    /// value is **>=** target (lower bound).
    private static func lowerBound(_ values: [Double], _ target: Double) -> Int {
        var low = 0
        var high = values.count
        while low < high {
            let mid = (low + high) / 2
            if values[mid] < target {
                low = mid + 1
            } else {
                high = mid
            }
        }
        return low
    }

    /// `np.searchsorted(times, target, side="right")`: the first index whose
    /// value is **>** target (upper bound).
    private static func upperBound(_ values: [Double], _ target: Double) -> Int {
        var low = 0
        var high = values.count
        while low < high {
            let mid = (low + high) / 2
            if values[mid] <= target {
                low = mid + 1
            } else {
                high = mid
            }
        }
        return low
    }
}
